---
name: CI
permissions: {}

on:
  push:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-macos:
    name: macOS
    permissions:
      contents: read
    uses: ./.github/workflows/ci-macos.yml
    with:
      publish_release: 'false'
      release_commit: ${{ github.sha }}
      release_version: '0.0.0'
